### ISSUE TITLE
JSON serialize fails for set() type in check result

### ISSUE THREAD

**Issue by Jan-M** [zalando/zmon-worker#15]
```
TypeError: set([u'i-0bfb11b2', u'i-29fdbe90', u'i-0305b6bb']) is not JSON serializable
```

**Comment by hjacobs** [comment]
:+1: this can easily be fixed by using a custom JSON serializer

**Comment by hjacobs** [comment]
I guess the same applies to "datetime" and "date" objects (but I think you cannot easily use them right now in a check command)..

**Comment by Jan-M** [comment]
Yeah I fixed this already using the one we use everywhere.

On Wednesday, 27 January 2016, Henning Jacobs <notifications@github.com>
wrote:

> [image: :+1:] this can easily be fixed by using a custom JSON serializer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zalando/zmon-worker/issues/15#issuecomment-175788025>.
>


-- 
Jan Mußler
Senior Database Engineer | +49 176 1275 8727 | Zalando SE

**Comment by Jan-M** [comment]
Closing this, http path now uses proper encoder.

This also affected captures and so on.
