### ISSUE TITLE
'NotaZmonTask' object has no attribute 'metric_cache_check_ids'

### ISSUE THREAD

**Issue by hjacobs** [zalando/zmon-worker#24]
I will NOT comment this bug... :speak_no_evil: 

Compare https://github.com/zalando/zmon-worker/blob/master/zmon_worker_monitor/zmon_worker/tasks/notacelery_task.py#L1044 and https://github.com/zalando/zmon-worker/blob/master/zmon_worker_monitor/zmon_worker/tasks/notacelery_task.py#L1364

**Comment by hjacobs** [comment]
Fixed and released with https://registry.opensource.zalan.do/teams/stups/artifacts/zmon-worker/tags/cd89/scm-source

**Comment by Jan-M** [comment]
I was pretty sure we had one unit test that covered our "not a celery" task execution? so when it went from failed to fixed I thought I was good.

Will look at IDE options again to get stupid auto complete. That's what you ment or? :palm_tree:
